name: hi
version: '1.2.0.1'
synopsis: Generate scaffold for cabal project
description: ! 'This application generates a scaffold for Haskell project from a Git
  repository.


  This command



  > $ hi foo-bar-baz



  will generate:



  > $ tree .

  > .

  > ├── LICENSE

  > ├── README.md

  > ├── foo-bar-baz.cabal

  > ├── src

  > │  └── Foo

  > │      └── Bar

  > │          ├── Baz

  > │          │  └── Internal.hs

  > │          └── Baz.hs

  > └── test

  >     ├── Foo

  >     │  └── Bar

  >     │      ├── Baz

  >     │      └── BazSpec.hs

  >     └── Spec.hs



  See <https://github.com/fujimura/hi> for further usage.

'
category: Distribution
author: Fujimura Daisuke
maintainer: me@fujimuradaisuke.com
license: BSD3
github: fujimura/hi.git
ghc-options: -Wall
source-dirs: src
dependencies:
- base ==4.*
- ansi-wl-pprint
- bytestring
- directory
- filepath
- optparse-applicative >=0.13.0
- parsec
- split
- template ==0.2.*
- text >1.0
- time
- process >=1.2.0.0
- temporary >=1.2.0.3
library:
  exposed-modules:
  - Hi
  - Hi.Cli
  - Hi.Config
  - Hi.Directory
  - Hi.FilePath
  - Hi.Git
  - Hi.Option
  - Hi.CommandLineOption
  - Hi.Template
  - Hi.Types
executables:
  hi:
    main: Main.hs
    source-dirs: app
tests:
  doctests:
    main: doctests.hs
    ghc-options: -threaded
    source-dirs: test
    dependencies:
    - hi
    - doctest >=0.8
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hi
    - HUnit
    - hspec >=2.0.0
    - silently
